export enum PermissionsEnum {
  // * MODULE:SUB-MODULE:PERMISSION
  SIPROAD_ADMIN          = 'SIPROAD:ALL:MANAGE',

  ADMIN_AUTH_LOGIN       = 'ADMIN:AUTH:LOGIN', 

  ADMIN_COMPANY_READ     = 'ADMIN:COMPANY:READ',
  ADMIN_COMPANY_WRITE    = 'ADMIN:COMPANY:WRITE',
  ADMIN_USER_READ        = 'ADMIN:USER:READ',
  ADMIN_USER_WRITE       = 'ADMIN:USER:WRITE',
  ADMIN_ROLE_READ        = 'ADMIN:ROLE:READ',
  ADMIN_ROLE_WRITE       = 'ADMIN:ROLE:WRITE',

  PRODUCTS_ADMIN_SETUP   = 'PRODUCTS:ADMIN:SETUP',
  PRODUCTS_PRODUCT_READ  = 'PRODUCTS:PRODUCT:READ',
  PRODUCTS_PRODUCT_WRITE = 'PRODUCTS:PRODUCT:WRITE',
  
  PURCHASES_ADMIN_SETUP   = 'PURCHASES:ADMIN:SETUP',
  PURCHASES_ORDER_READ    = 'PURCHASES:ORDER:READ',
  PURCHASES_ORDER_WRITE   = 'PURCHASES:ORDER:WRITE',
  PURCHASES_PROVIDER_READ = 'PURCHASES:PROVIDER:READ',
  PURCHASES_PROVIDER_WRITE= 'PURCHASES:PROVIDER:WRITE',

  SALES_ADMIN_SETUP      = 'SALES:ADMIN:SETUP',
  SALES_ORDER_READ       = 'SALES:ORDER:READ',
  SALES_ORDER_WRITE      = 'SALES:ORDER:WRITE',
  SALES_CUSTOMER_READ    = 'SALES:CUSTOMER:READ',
  SALES_CUSTOMER_WRITE   = 'SALES:CUSTOMER:WRITE'
}